### ISSUE TITLE
Not using nested style while scss

### ISSUE THREAD

**Issue by aslanforyou** [itsokto/exceedteam#2]
https://github.com/itsokto/exceedteam/blob/173f251268cff17ab53939fd58bfaeceb9e9aa55/todo-list-angular/src/app/todo-list/todo-list.component.scss#L14

why do not use nested structure?
like 
div {
  .class {

   }
}

**Comment by itsokto** [comment]
Because copy-paste from: https://github.com/itsokto/exceedteam/blob/6ac86c810af33b3fb7a659b3970d42273180580f/todo-list-jquery/src/todo.css#L18-L34
